[project]
authors = [
    {name = "Olamide Adebayo", email = "olamideadebayo2001@gmail.com"},
]
license = {text = "MIT"}
requires-python = "<4.0,>=3.10"
dependencies = [
    "anthropic<1.0.0,>=0.32.0",
    "python-dotenv<2.0.0,>=1.0.1",
    "tavily-python<1.0.0,>=0.3.6",
    "pillow<11.0.0,>=10.4.0",
    "rich<14.0.0,>=13.7.1",
    "prompt-toolkit<4.0.0,>=3.0.47",
    "pydantic<3.0.0,>=2.8.2",
    "litellm<2.0.0,>=1.49.2",
    "httpx<1.0.0,>=0.27.2",
    "pydantic-settings<3.0.0,>=2.6.0",
    "typer<1.0.0,>=0.14.0",
    "textual>=3.2.0",
]
name = "llm_engineer"
version = "0.0.1"
description = ""
readme = "README.md"

[project.scripts]
start = "llm_engineer.main:start"
codemason = "llm_engineer.cli:app"

[dependency-groups]
dev = [
    "black<25.0.0,>=24.8.0",
    "isort<6.0.0,>=5.13.2",
    "pytest<9.0.0,>=8.3.3",
    "pytest-cov<6.0.0,>=5.0.0",
    "pytest-mypy-plugins<4.0.0,>=3.1.2",
    "pytest-asyncio<1.0.0,>=0.24.0",
]

[tool.black]
line-length = 120
exclude = '''
(
  /(
      \.eggs         # exclude a few common directories in the
    | \.git          # root of the project
    | \.hg
    | \.mypy_cache
    | \.tox
    | \.venv
    | _build
    | buck-out
    | build
    | dist
  )/
)
'''

[tool.isort]
profile = "black"
skip = [
    '.eggs', '.git', '.hg', '.mypy_cache', '.nox', '.pants.d', '.tox',
    '.venv', '_build', 'buck-out', 'build', 'dist', 'node_modules', 'venv',
]
skip_gitignore = true

[tool.pytest.ini_options]
minversion = 7.0
addopts = "-ra -q -vv --cov=src tests/ --cov-report html --cov-report xml --cov-report term --mypy-extension-hook pytest_mypy_plugins.tests.reveal_type_hook.hook"

[tool.coverage.run]
branch = true
relative_files = true

[tool.coverage.report]
exclude_also = ["if __name__ == .__main__.:",]
fail_under = 84
precision = 2
show_missing = true
skip_empty = true

